dist: trusty
language: php

env:
  global:
    - TEST="./vendor/bin/phpunit --verbose"
    - COMPOSER_UP="composer update --no-interaction --prefer-dist --no-progress --profile --no-suggest"
    - secure: "yNc9OxDAmHaQM06Qs7p4IthL1xmpFDHBX1NvTEFAtY01GQOPhmJ0gbkJbbx02xHS0IJKP2GGANXl0YlQylXllKGosj7NhZm72z/+UiZm3kucuF7jNYomBf01Zn3gKjYUEME9e/wT3w5BZwl2hS4bTNmysjJVJQmRQdcxs4pOU6EmhMSmfMbmPnBxnbnCxA+jMlYFoSB/AUEaM3qhBrsqFapNSzrrc7qocJv+lD+CtaewqvNCEwpGnWPgTCUdbMOvI5f8Na+xsKAhnBZoS4lNHxsAKkK2cYmfIoL9I6F8iKfqzWvTLgENaEVVgz477FkUVSCeYkTsx5EmNJOeAJkBmwZPaV0fYB8E4YzfnlBkurAgqUItsedKHeDsK0dSv0t5Hr4FxQLVkBbQrpBWKhDC/1+a6nSFcke0g/JSZ1dwAS0OfS0PSrO4SWtVa0NEOBMW0izBswjoDzWhgHRSX29jGAbhB0WBHUMoxDsR8Kp3xbr8ytgef5DhDF3Udgd/iV//QByV++nz+42Z0JH2WY4chKcbSBJdLZ8dD0ajEyfoA2Pe3GYrXCnE2SKXsBSL1Md+DDbrg0gJPziPZszQ+LO89X4tAvAi0SewzKeqqAIBVUI8suQrNXti+1KRBHbAGxhpZ/MgjAIyS1+qIrnK3axVuG0uNrQ70940ls4CJjhJW0Q="

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - stty cols 120
  - chmod a+x ./build/travis/configure_php.sh
  - ./build/travis/configure_php.sh

install:
  - yarn install
  - cat yarn.lock | grep version
  - composer global require hirak/prestissimo
  - $COMPOSER_UP

jobs:
  allow_failures:
    - php: nightly
    - php: 7.4snapshot
  include:
    - stage: Test
      if: NOT type = cron
      php: 7.2
      env: REMOVE_XDEBUG=true
    - stage: Test
      if: NOT type = cron
      php: 7.3
      env: REMOVE_XDEBUG=true
    - stage: Test
      if: NOT type = cron
      php: 7.4
      env: REMOVE_XDEBUG=true
    - stage: Test
      if: NOT type = cron
      php: nightly
      env: REMOVE_XDEBUG=true

    - stage: Coding standard
      if: NOT type = cron
      php: 7.2
      env: REMOVE_XDEBUG=true
      script:
      - ./vendor/bin/php-cs-fixer fix --verbose --diff --dry-run

    - stage: Static Analysis
      if: NOT type = cron
      php: 7.2
      env: REMOVE_XDEBUG=false
      script:
      - ./vendor/bin/phpstan analyse -c phpstan.neon src

    - stage: Coverage
      if: type != cron
      php: 7.2
      env: REMOVE_XDEBUG=false
      script:
        - bash -xc "$TEST -c ./phpunit.xml.dist --coverage-clover=coverage.xml"
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: Build
      if: type = cron
      php: 7.4
      env: REMOVE_XDEBUG=true
      install:
        - yarn install
        - cat yarn.lock | grep version
        - composer global require --no-progress --no-scripts --no-plugins narrowspark/automatic-composer-prefetcher:dev-master
        - |
          cd ./build/command
          $COMPOSER_UP
          cd ../..
      before_script:
        - stty cols 120
        - |
          git config --global user.email "$GH_USER_EMAIL"
          git config --global user.name "$GH_USER_NAME"
          git remote set-url origin git@github.com:narrowspark/mimetypes.git
        - |
          chmod a+x ./build/travis/set_up_ssh.sh
          ./build/travis/set_up_ssh.sh
      script:
        - php ./build/command/cerebro build
        - php ./build/command/cerebro commit
        - rm -fr ./build/git/*

notifications:
  email:
    on_success: never
    on_failure: change
